import { createCryptoFlow, createHolding, deleteCryptoFlow, deleteHolding, saveCryptoSettings, updateHolding } from "@/app/actions";
import { ConfirmButton } from "@/components/ConfirmButton";
import { Kpi } from "@/components/Kpi";
import { SubmitButton } from "@/components/SubmitButton";
import { bdToday, money, number, shortDate } from "@/lib/format";
import { prisma } from "@/lib/prisma";

export default async function Crypto() {
  const [holdings, flows, settings] = await Promise.all([prisma.cryptoHolding.findMany({orderBy:{symbol:"asc"}}), prisma.cryptoFlow.findMany({orderBy:{date:"desc"}}), prisma.setting.findMany()]);
  const set=Object.fromEntries(settings.map(s=>[s.key,Number(s.value)])); const rate=set.exchangeRate||127; const available=set.availableUsdt||0;
  const current=holdings.reduce((s,h)=>s+Number(h.quantity)*Number(h.currentPriceUsdt),0); const cost=holdings.reduce((s,h)=>s+Number(h.costUsdt),0); const pl=current-cost;
  const capitalIn=flows.filter(f=>f.type==="BUY"||f.type==="DEPOSIT").reduce((s,f)=>s+Number(f.amountUsdt),0); const capitalOut=flows.filter(f=>f.type==="SELL"||f.type==="WITHDRAW").reduce((s,f)=>s+Number(f.amountUsdt),0);
  return <><div className="pageHead"><div><p className="eyebrow">USDT & holdings</p><h1>Crypto portfolio</h1><p>Manual prices and exchange rates only—LifeLedger never invents a live market price.</p></div></div><section className="kpiGrid"><Kpi label="Available USDT" value={`${number(available)} USDT`} note={money(available*rate)}/><Kpi label="Holdings value" value={`${number(current)} USDT`} note={money(current*rate)}/><Kpi label="Portfolio P/L" value={`${number(pl)} USDT`} note={money(pl*rate)} tone={pl>=0?"good":"bad"}/><Kpi label="Net capital" value={`${number(capitalIn-capitalOut)} USDT`} note={`In ${number(capitalIn)} · Out ${number(capitalOut)}`}/></section>
  <div className="twoCol"><section className="panel"><div className="panelHead"><div><h2>Key settings</h2><p>Update yellow cells from Excel here.</p></div></div><form action={saveCryptoSettings} className="formGrid"><label>Exchange rate (BDT/USDT)<input name="exchangeRate" type="number" step="0.01" defaultValue={rate}/></label><label>Available USDT<input name="availableUsdt" type="number" step="0.0001" defaultValue={available}/></label><div className="formActions wide"><SubmitButton>Save settings</SubmitButton></div></form></section><section className="panel"><div className="panelHead"><div><h2>Add capital flow</h2><p>Buy / deposit / sell / withdraw.</p></div></div><form action={createCryptoFlow} className="formGrid"><label>Date<input name="date" type="date" defaultValue={bdToday()} required/></label><label>Type<select name="type"><option value="BUY">Buy</option><option value="DEPOSIT">Deposit</option><option value="SELL">Sell</option><option value="WITHDRAW">Withdraw</option></select></label><label>USDT<input name="amountUsdt" type="number" step="0.0001" required/></label><label>Note<input name="note"/></label><div className="formActions wide"><SubmitButton>Add flow</SubmitButton></div></form></section></div>
  <section className="panel"><div className="panelHead"><div><h2>Holdings</h2></div></div><div className="tableWrap"><table><thead><tr><th>Asset</th><th>Quantity</th><th>Cost</th><th>Current price</th><th>Current value</th><th>P/L</th><th></th></tr></thead><tbody>{holdings.map(h=>{const val=Number(h.quantity)*Number(h.currentPriceUsdt);const hp=val-Number(h.costUsdt);return <tr key={h.id}><td><b>{h.symbol}</b></td><td colSpan={3}><form action={updateHolding} className="inlineForm"><input type="hidden" name="id" value={h.id}/><input name="quantity" type="number" min="0" step="0.00000001" defaultValue={String(h.quantity)}/><input name="costUsdt" type="number" min="0" step="0.0001" defaultValue={String(h.costUsdt)}/><input name="currentPriceUsdt" type="number" min="0" step="0.00000001" defaultValue={String(h.currentPriceUsdt)}/><input name="note" type="hidden" value={h.note||""}/><button className="miniBtn" type="submit">Save</button></form></td><td>{number(val)} USDT</td><td className={hp>=0?"positive":"negative"}>{number(hp)} USDT</td><td><form action={deleteHolding}><input type="hidden" name="id" value={h.id}/><ConfirmButton message={`Delete ${h.symbol} holding?`}/></form></td></tr>})}</tbody></table></div></section>
  <section className="panel narrow"><div className="panelHead"><div><h2>Add holding</h2></div></div><form action={createHolding} className="formGrid"><label>Symbol<input name="symbol" placeholder="BTC" required/></label><label>Quantity<input name="quantity" type="number" step="0.00000001" required/></label><label>Total cost (USDT)<input name="costUsdt" type="number" step="0.0001" required/></label><label>Current price (USDT)<input name="currentPriceUsdt" type="number" step="0.00000001" required/></label><label className="wide">Note<input name="note"/></label><div className="formActions wide"><SubmitButton>Add holding</SubmitButton></div></form></section>
  <section className="panel"><div className="panelHead"><div><h2>Capital flow history</h2></div></div><div className="tableWrap"><table><thead><tr><th>Date</th><th>Type</th><th>USDT</th><th>Note</th><th></th></tr></thead><tbody>{flows.map(f=><tr key={f.id}><td>{shortDate(f.date)}</td><td>{f.type}</td><td>{number(Number(f.amountUsdt))}</td><td>{f.note||"—"}</td><td><form action={deleteCryptoFlow}><input type="hidden" name="id" value={f.id}/><ConfirmButton message="Delete this crypto flow?"/></form></td></tr>)}</tbody></table></div></section>
  </>;
}
